### ISSUE TITLE
Label is not displayed

### ISSUE THREAD

**Issue by jcorrea-tkww** [royalswe/qliksense-extension-horizontal-list#1]
Hi,
I'm having issues displaying label 
Everything seems to work, but I cannot get the label being displayed
Is there any specific format I have to use ?

We are on Sep2020

![image](https://user-images.githubusercontent.com/52322349/104235799-c6d91180-5455-11eb-9cc8-931ec4c76e55.png)

**Comment by royalswe** [comment]
You add the label in the Appearance section, on the Title input.
I will remove the label input in Dimension section because it doesn't do anything.

**Comment by jcorrea-tkww** [comment]
I did that, but thi is the native Title placeholder so you cannot choose the position (top, left)

In that case, does it make sense to have "label position" (left, top,..) ?  It would be nice to have this label option included and working.  

Thanks @royalswe !

**Comment by royalswe** [comment]
Thanks for the tip @jcorrea-tkww 
The label is working now.
