### ISSUE TITLE
Is this OSS license an MIT license?

### ISSUE THREAD

**Issue by hsis1** [royalswe/qliksense-extension-horizontal-list#2]
Is this OSS license an MIT license?

As Permissions, Commercial use / Modification / Distribution / Private use

Is everything OK?

Are there any Limitations for using this OSS?

**Comment by royalswe** [comment]
Hi!
Yes it is MIT license and everything is OK.
There is no limitations.
Have fun with it :)

**Comment by hsis1** [comment]
I understand that there is no limitations.

I appreciate your quick response.
